### ISSUE TITLE
Images are not updated

### ISSUE THREAD

**Issue by gabbersepp** [maxime1992/dev-to-git#20]
If images, that were deployed to dev.to already, are updated, the new version is not visible.
I think this is due to caching.

StR:

Go to https://dev.to/maxime1992/manage-your-dev-to-blog-posts-from-a-git-repo-and-use-continuous-deployment-to-auto-publish-update-them-143j and see the image in "2. Create a dev.to token". The image should have been updated with my Pull Request but I am still seeing the old one.

**Comment by maxime1992** [comment]
Yup! This is beyond my control though. When I update an image URL, I usually add at the end `?bustCache=1` then increment that number if I update it again. Tested several times and it has always worked well :)
