### ISSUE TITLE
1.4.3 has no files in it

### ISSUE THREAD

**Issue by jmcdo29** [maxime1992/dev-to-git#48]
This may have been a side  effect of moving over to GitHub Actions. It looks like when [the release step ran, it only found a README, package.json and LICENSE](https://github.com/maxime1992/dev-to-git/runs/3332496773?check_suite_focus=true#step:10:59). Because of this, installing the latest package fails. You might want to make a `prerelease` step that runs the same as the `build` step so that you can make sure that when `release` is fired, it will have the current code.

**Comment by maxime1992** [comment]
Hey, indeed :scream: !

After some struggle to configure it correctly... 

![image](https://user-images.githubusercontent.com/4950209/129532497-b84839e2-b08f-4b4e-a04e-6335c68793b4.png)

I believe [v1.4.8](https://github.com/maxime1992/dev-to-git/releases/tag/v1.4.8) should have everything it needs. Can you confirm that it's working ok for you now and also that your previous fix is working ok? :)

**Comment by maxime1992** [comment]
Closing as I believe it's been fixed. 

Reopen if needed :+1:
