### ISSUE TITLE
Different Authors within one Repository

### ISSUE THREAD

**Issue by niklas-wortmann** [maxime1992/dev-to-git#9]
For out dev.to/rxjs (https://github.com/rxjs-blog/blog) organization I would like to have one central repository, where everyone can file prs to publish his article within the org. Therefore I would appreciate supporting authors on blog article level and not having one central dev.to user configured in the travis pipeline. I don't if that is even feasible?

Many thanks for maintaining this project. It helped me a lot with setting up the blogs!

**Comment by maxime1992** [comment]
Thanks for the kind words!

I'd love that as well, no idea how orgs are working though.

Because I'm 4 years late :sweat_smile: ... I'll just close this issue but if someone is willing to investigate let me know I'll reopen
